blumilksoftware/e-motion-api

Makefile, phpunit.xml
=> #31 - add database for testing

.github/CODEOWNERS
This pull request adds @blumilksoftware/blumilk and @blumilksoftware/blumilk-support to the code owners of this repository.
=> - code owners

resources/js/Pages/Cities/Components/City.vue, resources/js/Pages/Cities/Index.vue, resources/js/Pages/Countries/Components/Country.vue, resources/js/Pages/Countries/Index.vue, resources/js/Shared/Components/Pagination.vue, resources/js/Shared/Layout/AdminNavigation.vue, resources/js/Shared/Layout/Nav.vue, routes/web.php, tests/Feature/AdminTest.php, tests/Feature/CityControllerTest.php, tests/Feature/CountryControllerTest.php
Added hamburger menu for smaller screens in admin's panel, moved run importers button to admin's panel.
Number of changed files is caused by changing a few routes, so the actual changes are not that extensive
It should close #58.
=> #58 - mobile menu

app/Importers/VoiDataImporter.php, app/Jobs/VoiDataImporterJob.php, app/Services/DataImporterService.php, composer.lock
Voi is fully imported
It should close #21.
=> #21 - added Voi provider

app/Importers/NeuronDataImporter.php, app/Jobs/NeuronDataImporterJob.php, app/Services/DataImporterService.php
=> #26 - Neuron provider

.env.example, app/Exceptions/MapboxGeocodingServiceException.php, app/Importers/BirdDataImporter.php, app/Importers/BoltDataImporter.php, app/Importers/NeuronDataImporter.php, app/Jobs/BirdDataImporterJob.php, app/Services/DataImporterService.php, app/Services/MapboxGeocodingService.php, config/app.php, config/mapbox.php
=> #20 - Bird provider

resources/js/Shared/Components/Import.vue
=> #107 - fix display of logos

scripts/deploy.sh
=> - deploy fix

scripts/deploy.sh
=> - deploy fixes

resources/js/Shared/Layout/Map.vue
=> - rearranging tooltips

app/Importers/DataImporter.php, app/Importers/TierDataImporter.php, app/Jobs/TierDataImporterJob.php, app/Services/DataImporterService.php, app/Services/MapboxGeocodingService.php, database/seeders/ProviderSeeder.php, readme.md
Added Tier, updated readme.md
Modified MapboxGeocodingService - throwing an exception in getCoordinatesFromApi() wasn't helpful in any way. This stopped that particular importerJob and the result was that the remaining part of cities couldn't be fetched.
It should close #17
=> #17 - add Tier provider

app/Exceptions/ExceptionHandler.php, app/QueryBuilders/SortQuery.php, lang/pl/validation.php, resources/js/Shared/Components/InfoPopup.vue
Fix:
- 404 page after giving bad credentials in any form,
- sorting cities by providers,
- CSS.
=> - fix some bugs

.github/workflows/check-pr-title.yml
Added timeout to title workflow.
=> - workflow timeout

app/Exceptions/ExceptionHandler.php, composer.json, composer.lock
This PR adds Sentry integration for easier errors monitoring in non development environments.
Related issues:
- #56 
Closes #56
=> #56 - add Sentry

resources/js/Shared/Components/City.vue, resources/js/Shared/Components/ProviderIcons.vue
=> #161 - Make providers larger on hover 

routes/web.php, tests/Feature/SocialMediaLoginTest.php
=> #182 - add test for social media login

lang/pl.json, resources/js/Pages/Landing/SearchPanel.vue
=> #185 - Add information about the number of displayed cities

lang/en.json, lang/pl.json, resources/js/Pages/Landing/SearchPanel.vue
Updated code for correct genitive forms to display with result count. 
This should complete #185.
=> #185 - Add translations for search results and corrected genitive form in PL & EN

routes/api.php
This pr fixes routes problem during deployment
=> - fix api routes

app/Http/Controllers/Api/Admin/CityController.php, app/Http/Resources/CityWithoutAssignedCoordinatesResource.php, app/Http/Resources/CityWithoutAssignedCoordinatesResources.php
Added list of cities without coordinates, and count of cities without assigned country or coordinates as colleagues asked.
=> - Add count for cities without country or coordinates
